test_exception.o: test_exception.cpp Exception.hpp include.hpp
Exception.hpp:
include.hpp:
